global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Métricas do Prometheus
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Métricas da aplicação Spring Boot
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api:8080']
    scrape_interval: 5s

  # Métricas do sistema (Node Exporter)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Métricas do PostgreSQL
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Métricas do Loki
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
